"""Asserts the Python ports in src/ingestion and src/features reproduce the
real n8n JS exactly, using the golden fixtures captured under
tests/fixtures/n8n_js/ (generated by actually running the extracted JS in
Node -- see harness.js and WEATHER_KALSHI_TECHNICAL_PLAN.md Sec 3a)."""
import json
import pathlib
from datetime import datetime, timezone

import pytest

from src.features.actuals import eod_actuals_and_pressure
from src.features.daily_features import forecast_high
from src.ingestion.normalize import convert_to_f, normalize_nws_data, return_observations

FIXTURES_DIR = pathlib.Path(__file__).parent / "fixtures" / "n8n_js"


def load_fixture(name: str):
    with open(FIXTURES_DIR / "inputs" / f"{name}.json", encoding="utf-8") as f:
        raw_input = json.load(f)
    with open(FIXTURES_DIR / "golden" / f"{name}.json", encoding="utf-8") as f:
        golden = json.load(f)
    now = datetime.fromisoformat(golden["fixed_now"]).astimezone(timezone.utc)
    return raw_input, now, golden["output"]


def test_normalize_nws_data_matches_golden():
    raw_input, now, golden_output = load_fixture("normalize_normal")
    expected = [item["json"] for item in golden_output]
    actual = normalize_nws_data(raw_input, now)
    assert actual == expected


def test_forecast_high_matches_golden_normal_day():
    raw_input, now, golden_output = load_fixture("forecast_high_normal")
    expected = golden_output[0]["json"]
    actual = forecast_high(raw_input, now)
    assert actual == expected


def test_forecast_high_matches_golden_dst_day():
    raw_input, now, golden_output = load_fixture("forecast_high_dst")
    expected = golden_output[0]["json"]
    actual = forecast_high(raw_input, now)
    assert actual == expected
    # this is the buggy value, not the "correct" one -- see Sec 4 Step 2
    assert actual["lead_hours"] == pytest.approx(29.2)


def test_eod_actuals_and_pressure_matches_golden():
    raw_input, now, golden_output = load_fixture("eod_actuals_normal")
    expected = golden_output[0]["json"]
    actual = eod_actuals_and_pressure(raw_input, now)
    assert actual == expected


def test_convert_to_f_matches_golden():
    raw_input, now, golden_output = load_fixture("convert_to_f_normal")
    expected = [item["json"] for item in golden_output]
    actual = convert_to_f(raw_input, now)
    assert actual == expected


def test_return_observations_matches_golden():
    raw_input, _now, golden_output = load_fixture("return_observations_normal")
    expected = [item["json"] for item in golden_output]
    actual = return_observations(raw_input)
    assert actual == expected
